---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: add sudo
    yum:
      name: sudo
      state: latest
    when: ansible_distribution in ["CentOS","Debian"]
        
  - name: Install the latest version of Nano
    yum:
      name: nano
      state: latest

  - name: remove nano
    yum:
      name: nano
      state: removed 
   
