---
- hosts: all
  become: true
  pre_tasks:

  - name: add essentials sudo, nano, vim
    yum:
      name: 
        - sudo
        - nano
        - vim 
      state: latest
      update_cache: yes
      update_only: yes

  - name: remove nano 
    tags: MV 
    package:
      name: 
        - nano
      state: removed


- hosts: web_servers
  become: true
  tasks:

  - name: install webserver
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ webServer }}" 
        - "{{ programLanguage }}"
      state: latest
      update_cache: yes

  - name: copy default html file to slave
    tags: apache,apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/newIndex.html
      owner: root
      group: root
      mode: 0644

  - name: copy default html file to slave
    tags: apache,apache2, httpd
    copy:
      src: ./abc/a.html
      dest: /var/www/html/newIndexa.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb
      tags: centos,db,mariadb
      package:
        name: 
          - "{{ databaseServer }}"
          - "{{ databaseClient }}"
        state: latest

    - name: start "{{ databaseServer }}"
      service:
        name: mariadb
        enabled: yes
        state: restarted

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        stats: latest
        
